In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("hrdata.csv",index_col='Name')
df.head()

               Hire Date   Salary  Sick Days remaining
Name
Graham Chapman  03/15/14  50000.0                   10
John Cleese     06/01/15  65000.0                    8
Eric Idle       05/12/14  45000.0                   10
Terry Jones     11/01/13  70000.0                    3
Terry Gilliam   08/12/14  48000.0                    7

In [3]:
df = pd.read_csv("hrdata.csv")
df.head()

             Name Hire Date   Salary  Sick Days remaining
0  Graham Chapman  03/15/14  50000.0                   10
1     John Cleese  06/01/15  65000.0                    8
2       Eric Idle  05/12/14  45000.0                   10
3     Terry Jones  11/01/13  70000.0                    3
4   Terry Gilliam  08/12/14  48000.0                    7

In [5]:
df = pd.read_csv("hrdata.csv",parse_dates=['Hire Date'])
df.head()

C:\Users\pravi\AppData\Local\Temp\ipykernel_42936\1078521625.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv("hrdata.csv",parse_dates=['Hire Date'])

             Name  Hire Date   Salary  Sick Days remaining
0  Graham Chapman 2014-03-15  50000.0                   10
1     John Cleese 2015-06-01  65000.0                    8
2       Eric Idle 2014-05-12  45000.0                   10
3     Terry Jones 2013-11-01  70000.0                    3
4   Terry Gilliam 2014-08-12  48000.0                    7

In [6]:
df.to_csv('hrdata-modified.csv')