In [28]:
import pandas as pd

In [6]:
df = pd.read_excel('data.xlsm')

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df1 = df.head()

In [15]:
# create new csv file with 10 records
df1.to_csv('test_1.csv')

In [10]:
df1.to_csv('test_2.csv',index=False,header=False)

In [ ]:
df1.to_csv('test_3.csv',index=False,columns=['prodid','date'])

In [30]:
# df2 = pd.read_csv('weather_data.csv')
df2 = pd.read_csv('weather_data.csv',sep=',', na_values=[32],skiprows=[0,2],header=None,names=['date','temp1','temp2','season'])

In [31]:
df2

       date  temp1  temp2 season
0  1/1/2017    NaN      6   Rain
1  1/3/2017   28.0      2   Snow
2  1/4/2017   24.0      7   Snow
3  1/5/2017    NaN      4   Rain
4  1/6/2017   31.0      2  Sunny

In [32]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [33]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [18]:
df['Order ID']

0       CA-2016-152156
1       CA-2016-152156
2       CA-2016-138688
3       US-2015-108966
4       US-2015-108966
             ...
9989    CA-2014-110422
9990    CA-2017-121258
9991    CA-2017-121258
9992    CA-2017-121258
9993    CA-2017-119914
Name: Order ID, Length: 9994, dtype: object

In [19]:
type(df['Order ID'])

pandas.core.series.Series

In [20]:
df[['Order ID']]

            Order ID
0     CA-2016-152156
1     CA-2016-152156
2     CA-2016-138688
3     US-2015-108966
4     US-2015-108966
...              ...
9989  CA-2014-110422
9990  CA-2017-121258
9991  CA-2017-121258
9992  CA-2017-121258
9993  CA-2017-119914

[9994 rows x 1 columns]

In [21]:
type(df[['Order ID']])

pandas.core.frame.DataFrame

In [24]:
df[['City','Order ID']]

                 City        Order ID
0           Henderson  CA-2016-152156
1           Henderson  CA-2016-152156
2         Los Angeles  CA-2016-138688
3     Fort Lauderdale  US-2015-108966
4     Fort Lauderdale  US-2015-108966
...               ...             ...
9989            Miami  CA-2014-110422
9990       Costa Mesa  CA-2017-121258
9991       Costa Mesa  CA-2017-121258
9992       Costa Mesa  CA-2017-121258
9993      Westminster  CA-2017-119914

[9994 rows x 2 columns]

In [31]:
df4 = pd.read_html('https://www.basketball-reference.com/players/i/ibakase01.html')

In [32]:
len(df4)

11

In [35]:
df4[0].to_csv('players_data0.csv')

In [46]:
s = '''
{
    "name": "Pravin",
    "age": 21,
    "companies": ["Google", "Uber", "EY"]
}
'''

In [47]:
import json

In [48]:
s1 = json.loads(s)

In [49]:
s1

{'name': 'Pravin', 'age': 21, 'companies': ['Google', 'Uber', 'EY']}

In [50]:
pd.DataFrame(s1)

     name  age companies
0  Pravin   21    Google
1  Pravin   21      Uber
2  Pravin   21        EY

In [51]:
pd.DataFrame(s1,columns=['companies'])

  companies
0    Google
1      Uber
2        EY

In [52]:
import requests

In [53]:
res = requests.get('https://api.github.com/repos/pandas-dev/pandas/issues')

In [54]:
res

In [55]:
data = res.json()

In [56]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
  'id': 2942576054,
  'node_id': 'PR_kwDOAA0YD86P1abm',
  'number': 61173,
  'title': 'BUG: Handle line and bar on the same plot',
  'user': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-24T09:22:19Z',
  'updated_at': '2025-03-25T03:46:55Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61173',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61173',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61173.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61173.patch',
   'merged_at': None},
  'body': "- [x] closes #61161\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\nThis code\r\n```python\r\nimport pandas as pd\r\nimport matplotlib.pyplot as plt\r\n\r\nindex = pd.period_range('2023', periods=3, freq='Y')\r\ndf = pd.DataFrame({\r\n    'col1': [10, 20, 30],\r\n    'col2': [40, 25, 10]\r\n}, index=index)\r\n\r\nfig, ax = plt.subplots()\r\ndf['col1'].plot(kind='bar', ax=ax)\r\nax2 = ax.twinx()\r\ndf['col2'].plot(kind='line', ax=ax2, color = 'r')\r\nplt.show()\r\n```\r\nfrom the linked issue gives this plot:\r\n![image](https://github.com/user-attachments/assets/9732188c-5478-4e93-ae3c-ae18e77776f3)\r\n\r\nAnd swapping the lines (line before bar)\r\n```python\r\ndf['col2'].plot(kind='line', ax=ax2, color = 'r')\r\ndf['col1'].plot(kind='bar', ax=ax)\r\n```\r\ngives\r\n![image](https://github.com/user-attachments/assets/35815445-dd3d-4a95-8c27-5a4dd07810be)\r\n\r\nI believe the difference of results stems from the fact that the figure is always cropped to match the x-range of the last plot. We can certainly adjust the PR to make the first figure behave like the second one if desired.\r\n\r\nPlease provide feedback on the overall approach. Once confirmed, I'll expand and cover with tests.\r\n",
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61173/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61172',
  'id': 2941851698,
  'node_id': 'I_kwDOAA0YD86vWRgy',
  'number': 61172,
  'title': 'BUG: pd.read_csv() on empty files should give an empty dataframe pd.DataFrame()',
  'user': {'login': 'xuancong84',
   'id': 10172392,
   'node_id': 'MDQ6VXNlcjEwMTcyMzky',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10172392?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/xuancong84',
   'html_url': 'https://github.com/xuancong84',
   'followers_url': 'https://api.github.com/users/xuancong84/followers',
   'following_url': 'https://api.github.com/users/xuancong84/following{/other_user}',
   'gists_url': 'https://api.github.com/users/xuancong84/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/xuancong84/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/xuancong84/subscriptions',
   'organizations_url': 'https://api.github.com/users/xuancong84/orgs',
   'repos_url': 'https://api.github.com/users/xuancong84/repos',
   'events_url': 'https://api.github.com/users/xuancong84/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/xuancong84/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv'},
   {'id': 2365504893,
    'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate',
    'name': 'Closing Candidate',
    'color': 'be21f2',
    'default': False,
    'description': 'May be closeable, needs more eyeballs'}],
  'state': 'open',
  'locked': False,
  'assignee': {'login': 'MartinBraquet',
   'id': 25173236,
   'node_id': 'MDQ6VXNlcjI1MTczMjM2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MartinBraquet',
   'html_url': 'https://github.com/MartinBraquet',
   'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
   'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
   'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
   'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
   'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'assignees': [{'login': 'MartinBraquet',
    'id': 25173236,
    'node_id': 'MDQ6VXNlcjI1MTczMjM2',
    'avatar_url': 'https://avatars.githubusercontent.com/u/25173236?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/MartinBraquet',
    'html_url': 'https://github.com/MartinBraquet',
    'followers_url': 'https://api.github.com/users/MartinBraquet/followers',
    'following_url': 'https://api.github.com/users/MartinBraquet/following{/other_user}',
    'gists_url': 'https://api.github.com/users/MartinBraquet/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/MartinBraquet/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/MartinBraquet/subscriptions',
    'organizations_url': 'https://api.github.com/users/MartinBraquet/orgs',
    'repos_url': 'https://api.github.com/users/MartinBraquet/repos',
    'events_url': 'https://api.github.com/users/MartinBraquet/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/MartinBraquet/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False}],
  'milestone': None,
  'comments': 4,
  'created_at': '2025-03-24T03:07:45Z',
  'updated_at': '2025-03-25T00:50:55Z',
  'closed_at': None,
  'author_association': 'NONE',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [x] I have checked that this issue has not already been reported.\n\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\n\n\n### Reproducible Example\n\n```python\nUsing `pd.read_csv()` to open an empty CSV file (0-bytes file or single-byte file (EOL character) by VIM) will give the following error:\n\nTraceback (most recent call last):\n  File "<stdin>", line 1, in <module>\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv\n    return _read(filepath_or_buffer, kwds)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read\n    parser = TextFileReader(filepath_or_buffer, **kwds)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__\n    self._engine = self._make_engine(f, self.engine)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine\n    return mapping[engine](f, **self.options)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/xuancong/anaconda3/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__\n    self._reader = parsers.TextReader(src, **kwds)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__\npandas.errors.EmptyDataError: No columns to parse from file\n```\n\n### Issue Description\n\nThe reason of the crash is that there is no columns to parse. However, Pandas does allow dataframes with no columns and no rows, i.e., `pd.DataFrame()` gives an empty DataFrame with no rows and no columns.\n\nThe logic reasoning is that if opening an empty CSV will cause crash, then **opening what kind of CSV file will give rise to an empty DataFrame**? When designing APIs, one fundamental principle is to try to keep a 1-to-1 mapping between input and output (so as to reduce information loss); thus, in this case, it is the mapping between CSV file and dataframe. I do agree that if the CSV does not exist or cannot be read (due to permission), then the call should crash. But if the CSV file is empty, `pd.read_csv()` should give an empty dataframe because empty dataframe does exist. Otherwise, what text should I put into a CSV file so that `pd.read_csv()` will give an empty DataFrame, i.e., `pd.DataFrame()`? Thanks!\n\n### Expected Behavior\n\nOpening an empty CSV file should give an empty DataFrame (i.e., pd.DataFrame()):\n```\nEmpty DataFrame\nColumns: []\nIndex: []\n```\n\n### Installed Versions\n\n<details>\n\nINSTALLED VERSIONS\n------------------\ncommit                : 0691c5cf90477d3503834d983f69350f250a6ff7\npython                : 3.11.5\npython-bits           : 64\nOS                    : Linux\nOS-release            : 6.8.0-52-generic\nVersion               : #53~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 15 19:18:46 UTC 2\nmachine               : x86_64\nprocessor             : x86_64\nbyteorder             : little\nLC_ALL                : en_US.UTF-8\nLANG                  : en_US.UTF-8\nLOCALE                : en_US.UTF-8\n\npandas                : 2.2.3\nnumpy                 : 1.26.4\npytz                  : 2023.3.post1\ndateutil              : 2.8.2\npip                   : 25.0.1\nCython                : None\nsphinx                : 5.0.2\nIPython               : 8.15.0\nadbc-driver-postgresql: None\nadbc-driver-sqlite    : None\nbs4                   : 4.12.2\nblosc                 : None\nbottleneck            : 1.4.0\ndataframe-api-compat  : None\nfastparquet           : None\nfsspec                : 2025.2.0\nhtml5lib              : None\nhypothesis            : None\ngcsfs                 : None\njinja2                : 3.1.2\nlxml.etree            : 4.9.3\nmatplotlib            : 3.8.4\nnumba                 : 0.60.0\nnumexpr               : 2.8.4\nodfpy                 : None\nopenpyxl              : None\npandas_gbq            : None\npsycopg2              : None\npymysql               : None\npyarrow               : 11.0.0\npyreadstat            : None\npytest                : 7.4.0\npython-calamine       : None\npyxlsb                : None\ns3fs                  : None\nscipy                 : 1.14.1\nsqlalchemy            : None\ntables                : 3.9.2\ntabulate              : None\nxarray                : 2023.6.0\nxlrd                  : None\nxlsxwriter            : 3.2.2\nzstandard             : 0.19.0\ntzdata                : 2023.3\nqtpy                  : None\npyqt5                 : None\n\n\n</details>\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61172/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
  'id': 2941462140,
  'node_id': 'PR_kwDOAA0YD86Pxsxt',
  'number': 61171,
  'title': 'DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',
   'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2025-03-23T20:16:22Z',
  'updated_at': '2025-03-25T03:24:32Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'type': None,
  'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61171',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/61171.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/61171.patch',
   'merged_at': None},
  'body': '- [x] closes #61170  (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'closed_by': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61170/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/61170',
  'id': 2941455212,
  'node_id': 'I_kwDOAA0YD86vUwts',
  'number': 61170,
  'title': 'BUG: DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
  'user': {'login': 'Aliebc',
   'id': 89406058,
   'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Aliebc',
   'html_url': 'https://github.com/Aliebc',
   'followers_url': 'https://api.github.com/users/Aliebc/followers',
   'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
   'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
   'repos_url': 'https://api.github.com/users/Aliebc/repos',

In [58]:
data[2]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
 'id': 2941462140,
 'node_id': 'PR_kwDOAA0YD86Pxsxt',
 'number': 61171,
 'title': 'DataFrame.dtypes.to_json OverflowError: Maximum recursion level reached',
 'user': {'login': 'Aliebc',
  'id': 89406058,
  'node_id': 'MDQ6VXNlcjg5NDA2MDU4',
  'avatar_url': 'https://avatars.githubusercontent.com/u/89406058?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/Aliebc',
  'html_url': 'https://github.com/Aliebc',
  'followers_url': 'https://api.github.com/users/Aliebc/followers',
  'following_url': 'https://api.github.com/users/Aliebc/following{/other_user}',
  'gists_url': 'https://api.github.com/users/Aliebc/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/Aliebc/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/Aliebc/subscriptions',
  'organizations_url': 'https://api.github.com/users/Aliebc/orgs',
  'repos_url': 'https://api.github.com/users/Aliebc/repos',
  'events_url': 'https://api.github.com/users/Aliebc/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/Aliebc/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2025-03-23T20:16:22Z',
 'updated_at': '2025-03-25T03:24:32Z',
 'closed_at': None,
 'author_association': 'CONTRIBUTOR',
 'type': None,
 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0},
 'active_lock_reason': None,
 'draft': False,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/61171',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61171',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/61171.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/61171.patch',
  'merged_at': None},
 'body': '- [x] closes #61170  (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
 'closed_by': None,
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61171/timeline',
 'performed_via_github_app': None,
 'state_reason': None}

In [60]:
df5 = pd.DataFrame(data)

In [61]:
df5[['title','url']]

,title,url
0,BUG: Handle line and bar on the same plot,https://api.github.com/repos/pandas-dev/pandas...
1,BUG: pd.read_csv() on empty files should give ...,https://api.github.com/repos/pandas-dev/pandas...
2,DataFrame.dtypes.to_json OverflowError: Maximu...,https://api.github.com/repos/pandas-dev/pandas...
3,BUG: DataFrame.dtypes.to_json OverflowError: M...,https://api.github.com/repos/pandas-dev/pandas...
4,ENH: Accept no fields for groupby by,https://api.github.com/repos/pandas-dev/pandas...
5,ENH: Enable nsmallest/nlargest on object dtype,https://api.github.com/repos/pandas-dev/pandas...
6,ENH: merge_asof threshold minimum,https://api.github.com/repos/pandas-dev/pandas...
7,"WEB: Remove self (Marco Gorelli) from ""active ...",https://api.github.com/repos/pandas-dev/pandas...
8,ENH: Support boolean masks for `iloc.__getitem__`,https://api.github.com/repos/pandas-dev/pandas...
9,BUG: fails to plot 2 plots with secondary y ax...,https://api.github.com/repos/pandas-dev/pandas...
10,ENH: Accept no fields for groupby by,https://api.github.com/repos/pandas-dev/pandas...
11,Csv func,https://api.github.com/repos/pandas-dev/pandas...
12,BUILD: Cython.Compiler.Errors: 'free_threading...,https://api.github.com/repos/pandas-dev/pandas...
13,BUG: Impossible creation of array with dtype=s...,https://api.github.com/repos/pandas-dev/pandas...
14,BUG: Clip corr edge cases between -1.0 and 1.0,https://api.github.com/repos/pandas-dev/pandas...
15,BUG: import pandas 2.2.3 on WSL 2.4.12.0 raise...,https://api.github.com/repos/pandas-dev/pandas...
16,ENH: Adds `dict` & `**dict` support for `pd.se...,https://api.github.com/repos/pandas-dev/pandas...
17,ENH: Added dict support for `pd.set_option`,https://api.github.com/repos/pandas-dev/pandas...
18,BUG: Added deprecation warning to Timestamp co...,https://api.github.com/repos/pandas-dev/pandas...
19,String dtype: more informative repr (keeping b...,https://api.github.com/repos/pandas-dev/pandas...
20,BUG: Inconsistent index type when using read_c...,https://api.github.com/repos/pandas-dev/pandas...
21,BUG(?): rolling sum with pyarrow types results...,https://api.github.com/repos/pandas-dev/pandas...
22,Preserve column names in empty Dataframe,https://api.github.com/repos/pandas-dev/pandas...
23,BUG: Collision between equivalent frequencies ...,https://api.github.com/repos/pandas-dev/pandas...
24,BUG: `DataFrame.from_records()` ignores `colum...,https://api.github.com/repos/pandas-dev/pandas...
25,API (string dtype): implement hierarchy (NA > ...,https://api.github.com/repos/pandas-dev/pandas...
26,Improve the apply/map APIs,https://api.github.com/repos/pandas-dev/pandas...
27,DOC: Write user guide page on apply/map/transf...,https://api.github.com/repos/pandas-dev/pandas...
28,ENH: Supporting third-party engines for all `m...,https://api.github.com/repos/pandas-dev/pandas...
29,ENH: fillna enhancement with method='nearest',https://api.github.com/repos/pandas-dev/pandas...

In [62]:
len(data)

30

In [69]:

userDataList = []

for i in range(len(data)):
    userDataList.append(data[i]['user'])

In [71]:
userDF = pd.DataFrame(userDataList)

In [73]:
userDF

,login,id,node_id,avatar_url,gravatar_id,url,html_url,followers_url,following_url,gists_url,starred_url,subscriptions_url,organizations_url,repos_url,events_url,received_events_url,type,user_view_type,site_admin
0,MartinBraquet,25173236,MDQ6VXNlcjI1MTczMjM2,https://avatars.githubusercontent.com/u/251732...,,https://api.github.com/users/MartinBraquet,https://github.com/MartinBraquet,https://api.github.com/users/MartinBraquet/fol...,https://api.github.com/users/MartinBraquet/fol...,https://api.github.com/users/MartinBraquet/gis...,https://api.github.com/users/MartinBraquet/sta...,https://api.github.com/users/MartinBraquet/sub...,https://api.github.com/users/MartinBraquet/orgs,https://api.github.com/users/MartinBraquet/repos,https://api.github.com/users/MartinBraquet/eve...,https://api.github.com/users/MartinBraquet/rec...,User,public,False
1,xuancong84,10172392,MDQ6VXNlcjEwMTcyMzky,https://avatars.githubusercontent.com/u/101723...,,https://api.github.com/users/xuancong84,https://github.com/xuancong84,https://api.github.com/users/xuancong84/followers,https://api.github.com/users/xuancong84/follow...,https://api.github.com/users/xuancong84/gists{...,https://api.github.com/users/xuancong84/starre...,https://api.github.com/users/xuancong84/subscr...,https://api.github.com/users/xuancong84/orgs,https://api.github.com/users/xuancong84/repos,https://api.github.com/users/xuancong84/events...,https://api.github.com/users/xuancong84/receiv...,User,public,False
2,Aliebc,89406058,MDQ6VXNlcjg5NDA2MDU4,https://avatars.githubusercontent.com/u/894060...,,https://api.github.com/users/Aliebc,https://github.com/Aliebc,https://api.github.com/users/Aliebc/followers,https://api.github.com/users/Aliebc/following{...,https://api.github.com/users/Aliebc/gists{/gis...,https://api.github.com/users/Aliebc/starred{/o...,https://api.github.com/users/Aliebc/subscriptions,https://api.github.com/users/Aliebc/orgs,https://api.github.com/users/Aliebc/repos,https://api.github.com/users/Aliebc/events{/pr...,https://api.github.com/users/Aliebc/received_e...,User,public,False
3,Aliebc,89406058,MDQ6VXNlcjg5NDA2MDU4,https://avatars.githubusercontent.com/u/894060...,,https://api.github.com/users/Aliebc,https://github.com/Aliebc,https://api.github.com/users/Aliebc/followers,https://api.github.com/users/Aliebc/following{...,https://api.github.com/users/Aliebc/gists{/gis...,https://api.github.com/users/Aliebc/starred{/o...,https://api.github.com/users/Aliebc/subscriptions,https://api.github.com/users/Aliebc/orgs,https://api.github.com/users/Aliebc/repos,https://api.github.com/users/Aliebc/events{/pr...,https://api.github.com/users/Aliebc/received_e...,User,public,False
4,udit710,103230240,U_kgDOBicrIA,https://avatars.githubusercontent.com/u/103230...,,https://api.github.com/users/udit710,https://github.com/udit710,https://api.github.com/users/udit710/followers,https://api.github.com/users/udit710/following...,https://api.github.com/users/udit710/gists{/gi...,https://api.github.com/users/udit710/starred{/...,https://api.github.com/users/udit710/subscript...,https://api.github.com/users/udit710/orgs,https://api.github.com/users/udit710/repos,https://api.github.com/users/udit710/events{/p...,https://api.github.com/users/udit710/received_...,User,public,False
5,Gri72,61454390,MDQ6VXNlcjYxNDU0Mzkw,https://avatars.githubusercontent.com/u/614543...,,https://api.github.com/users/Gri72,https://github.com/Gri72,https://api.github.com/users/Gri72/followers,https://api.github.com/users/Gri72/following{/...,https://api.github.com/users/Gri72/gists{/gist...,https://api.github.com/users/Gri72/starred{/ow...,https://api.github.com/users/Gri72/subscriptions,https://api.github.com/users/Gri72/orgs,https://api.github.com/users/Gri72/repos,https://api.github.com/users/Gri72/events{/pri...,https://api.github.com/users/Gri72/received_ev...,User,public,False
6,Lituchy,41648348,MDQ6VXNlcjQxNjQ4MzQ4,https://avatars.githubusercontent.com/u/416483...,,https://api.github.com/users/Lituchy,https://github.com/Lituchy,https://api.github.com/users/Lituchy/followers,https://api.github.com/users/Lituchy/following...,https://api.github.com/users/Lituchy/gists{/gi...,https://api.github.com/users/Lituchy/starred{/...,https://api.github.com/users/Lituchy/subscript...,https://api.github.com/users/Lituchy/orgs,https://api.github.com/users/Lituchy/repos,https://api.github.com/users/Lituchy/events{/p...,https://api.github.com/users/Lituchy/received_...,User,public,False
7,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,public,False
8,arthurlw,126365160,U_kgDOB4gt6A,https://avatars.githubusercontent.com/u/126365...,,https://api.github.com/users/arthurlw,https://github.com/arthurlw,https://api.github.com/users/arthurlw/followers,https://api.github.com/users/arthurlw/followin...,https://api.github.com/users/arthurlw/gists{/g...,https://api.github.com/users/arthurlw/starred{...,https://api.github.com/users/arthurlw/subscrip...,https://api.github.com/users/arthurlw/orgs,https://api.github.com/users/arthurlw/repos,https://api.github.com/users/arthurlw/events{/...,https://api.github.com/users/arthurlw/received...,User,public,False
9,Ev2geny,59611075,MDQ6VXNlcjU5NjExMDc1,https://avatars.githubusercontent.com/u/596110...,,https://api.github.com/users/Ev2geny,https://github.com/Ev2geny,https://api.github.com/users/Ev2geny/followers,https://api.github.com/users/Ev2geny/following...,https://api.github.com/users/Ev2geny/gists{/gi...,https://api.github.com/users/Ev2geny/starred{/...,https://api.github.com/users/Ev2geny/subscript...,https://api.github.com/users/Ev2geny/orgs,https://api.github.com/users/Ev2geny/repos,https://api.github.com/users/Ev2geny/events{/p...,https://api.github.com/users/Ev2geny/received_...,User,public,False
10,simonaubertbd,46959192,MDQ6VXNlcjQ2OTU5MTky,https://avatars.githubusercontent.com/u/469591...,,https://api.github.com/users/simonaubertbd,https://github.com/simonaubertbd,https://api.github.com/users/simonaubertbd/fol...,https://api.github.com/users/simonaubertbd/fol...,https://api.github.com/users/simonaubertbd/gis...,https://api.github.com/users/simonaubertbd/sta...,https://api.github.com/users/simonaubertbd/sub...,https://api.github.com/users/simonaubertbd/orgs,https://api.github.com/users/simonaubertbd/repos,https://api.github.com/users/simonaubertbd/eve...,https://api.github.com/users/simonaubertbd/rec...,User,public,False
11,Jaspvr,114035580,U_kgDOBswLfA,https://avatars.githubusercontent.com/u/114035...,,https://api.github.com/users/Jaspvr,https://github.com/Jaspvr,https://api.github.com/users/Jaspvr/followers,https://api.github.com/users/Jaspvr/following{...,https://api.github.com/users/Jaspvr/gists{/gis...,https://api.github.com/users/Jaspvr/starred{/o...,https://api.github.com/users/Jaspvr/subscriptions,https://api.github.com/users/Jaspvr/orgs,https://api.github.com/users/Jaspvr/repos,https://api.github.com/users/Jaspvr/events{/pr...,https://api.github.com/users/Jaspvr/received_e...,User,public,False
12,yohplala,13206058,MDQ6VXNlcjEzMjA2MDU4,https://avatars.githubusercontent.com/u/132060...,,https://api.github.com/users/yohplala,https://github.com/yohplala,https://api.github.com/users/yohplala/followers,https://api.github.com/users/yohplala/followin...,https://api.github.com/users/yohplala/gists{/g...,https://api.github.com/users/yohplala/starred{...,https://api.github.com/users/yohplala/subscrip...,https://api.github.com/users/yohplala/orgs,https://api.github.com/users/yohplala/repos,https://api.github.com/users/yohplala/events{/...,https://api.github.com/users/yohplala/received...,User,public,False
13,Maxence1402,29152218,MDQ6VXNlcjI5MTUyMjE4,https://avatars.githubusercontent.com/u/291522...,,https://api.github.com/users/Maxence1402,https://github.com/Maxence1402,https://api.github.com/users/Maxence1402/follo...,https://api.github.com/users/Maxence1402/follo...,https://api.github.com/users/Maxence1402/gists...,https://api.github.com/users/Maxence1402/starr...,https://api.github.com/users/Maxence1402/subsc...,https://api.github.com/users/Maxence1402/orgs,https://api.github.com/users/Maxence1402/repos,https://api.github.com/users/Maxence1402/event...,https://api.github.com/users/Maxence1402/recei...,User,public,False
14,j-hendricks,105813545,U_kgDOBk6WKQ,https://avatars.githubusercontent.com/u/105813...,,https://api.github.com/users/j-hendricks,https://github.com/j-hendricks,https://api.github.com/users/j-hendricks/follo...,https://api.github.com/users/j-hendricks/follo...,https://api.github.com/users/j-hendricks/gists...,https://api.github.com/users/j-hendricks/starr...,https://api.github.com/users/j-hendricks/subsc...,https://api.github.com/users/j-hendricks/orgs,https://api.github.com/users/j-hendricks/repos,https://api.github.com/users/j-hendricks/event...,https://api.github.com/users/j-hendricks/recei...,User,public,False
15,pierre-eliep-met,97044708,U_kgDOBcjI5A,https://avatars.githubusercontent.com/u/970447...,,https://api.github.com/users/pierre-eliep-met,https://github.com/pierre-eliep-met,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,https://api.github.com/users/pierre-eliep-met/...,User,public,False
16,himanshumahajan138,83700343,MDQ6VXNlcjgzNzAwMzQz,https://avatars.githubusercontent.com/u/837003...,,https://api.github.com/users/himanshumahajan138,https://github.com/himanshumahajan138,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,https://api.github.com/users/himanshumahajan13...,User,public,False
17,arthurlw,126365160,U_kgDOB4gt6A,https://avatars.githubusercontent.com/u/126365...,,https://api.github.com/users/arthurlw,https://github.com/arthurlw,https://api.github.com/users/arthurlw/followers,https://api.github.com/users/arthurlw/followin...,https://api.github.com/users/arthurlw/gists{/g...,https://api.github.com/users/arthurlw/starred{...,https://api.github.com/users/arthurlw/subscrip...,https://api.github.com/users/arthurlw/orgs,https://api.github.com/users/arthurlw/repos,https://api.github.com/users/arthurlw/events{/...,https://api.github.com/users/arthurlw/received...,User,public,False
18,j-hendricks,105813545,U_kgDOBk6WKQ,https://avatars.githubusercontent.com/u/105813...,,https://api.github.com/users/j-hendricks,https://github.com/j-hendricks,https://api.github.com/users/j-hendricks/follo...,https://api.github.com/users/j-hendricks/follo...,https://api.github.com/users/j-hendricks/gists...,https://api.github.com/users/j-hendricks/starr...,https://api.github.com/users/j-hendricks/subsc...,https://api.github.com/users/j-hendricks/orgs,https://api.github.com/users/j-hendricks/repos,https://api.github.com/users/j-hendricks/event...,https://api.github.com/users/j-hendricks/recei...,User,public,False
19,jorisvandenbossche,1020496,MDQ6VXNlcjEwMjA0OTY=,https://avatars.githubusercontent.com/u/102049...,,https://api.github.com/users/jorisvandenbossche,https://github.com/jorisvandenbossche,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,User,public,False
20,ptth222,25493640,MDQ6VXNlcjI1NDkzNjQw,https://avatars.githubusercontent.com/u/254936...,,https://api.github.com/users/ptth222,https://github.com/ptth222,https://api.github.com/users/ptth222/followers,https://api.github.com/users/ptth222/following...,https://api.github.com/users/ptth222/gists{/gi...,https://api.github.com/users/ptth222/starred{/...,https://api.github.com/users/ptth222/subscript...,https://api.github.com/users/ptth222/orgs,https://api.github.com/users/ptth222/repos,https://api.github.com/users/ptth222/events{/p...,https://api.github.com/users/ptth222/received_...,User,public,False
21,MarcoGorelli,33491632,MDQ6VXNlcjMzNDkxNjMy,https://avatars.githubusercontent.com/u/334916...,,https://api.github.com/users/MarcoGorelli,https://github.com/MarcoGorelli,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/foll...,https://api.github.com/users/MarcoGorelli/gist...,https://api.github.com/users/MarcoGorelli/star...,https://api.github.com/users/MarcoGorelli/subs...,https://api.github.com/users/MarcoGorelli/orgs,https://api.github.com/users/MarcoGorelli/repos,https://api.github.com/users/MarcoGorelli/even...,https://api.github.com/users/MarcoGorelli/rece...,User,public,False
22,kpvenkat47,87000728,MDQ6VXNlcjg3MDAwNzI4,https://avatars.githubusercontent.com/u/870007...,,https://api.github.com/users/kpvenkat47,https://github.com/kpvenkat47,https://api.github.com/users/kpvenkat47/followers,https://api.github.com/users/kpvenkat47/follow...,https://api.github.com/users/kpvenkat47/gists{...,https://api.github.com/users/kpvenkat47/starre...,https://api.github.com/users/kpvenkat47/subscr...,https://api.github.com/users/kpvenkat47/orgs,https://api.github.com/users/kpvenkat47/repos,https://api.github.com/users/kpvenkat47/events...,https://api.github.com/users/kpvenkat47/receiv...,User,public,False
23,ycdjun,47006276,MDQ6VXNlcjQ3MDA2Mjc2,https://avatars.githubusercontent.com/u/470062...,,https://api.github.com/users/ycdjun,https://github.com/ycdjun,https://api.github.com/users/ycdjun/followers,https://api.github.com/users/ycdjun/following{...,https://api.github.com/users/ycdjun/gists{/gis...,https://api.github.com/users/ycdjun/starred{/o...,https://api.github.com/users/ycdjun/subscriptions,https://api.github.com/users/ycdjun/orgs,https://api.github.com/users/ycdjun/repos,https://api.github.com/users/ycdjun/events{/pr...,https://api.github.com/users/ycdjun/received_e...,User,public,False
24,jlumpe,7455396,MDQ6VXNlcjc0NTUzOTY=,https://avatars.githubusercontent.com/u/745539...,,https://api.github.com/users/jlumpe,https://github.com/jlumpe,https://api.github.com/users/jlumpe/followers,https://api.github.com/users/jlumpe/following{...,https://api.github.com/users/jlumpe/gists{/gis...,https://api.github.com/users/jlumpe/starred{/o...,https://api.github.com/users/jlumpe/subscriptions,https://api.github.com/users/jlumpe/orgs,https://api.github.com/users/jlumpe/repos,https://api.github.com/users/jlumpe/events{/pr...,https://api.github.com/users/jlumpe/received_e...,User,public,False
25,jorisvandenbossche,1020496,MDQ6VXNlcjEwMjA0OTY=,https://avatars.githubusercontent.com/u/102049...,,https://api.github.com/users/jorisvandenbossche,https://github.com/jorisvandenbossche,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,https://api.github.com/users/jorisvandenbossch...,User,public,False
26,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,public,False
27,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,public,False
28,datapythonista,10058240,MDQ6VXNlcjEwMDU4MjQw,https://avatars.githubusercontent.com/u/100582...,,https://api.github.com/users/datapythonista,https://github.com/datapythonista,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/fo...,https://api.github.com/users/datapythonista/gi...,https://api.github.com/users/datapythonista/st...,https://api.github.com/users/datapythonista/su...,https://api.github.com/users/datapythonista/orgs,https://api.github.com/users/datapythonista/repos,https://api.github.com/users/datapythonista/ev...,https://api.github.com/users/datapythonista/re...,User,public,False
29,mennowitteveen,6292714,MDQ6VXNlcjYyOTI3MTQ=,https://avatars.githubusercontent.com/u/629271...,,https://api.github.com/users/mennowitteveen,https://github.com/mennowitteveen,https://api.github.com/users/mennowitteveen/fo...,https://api.github.com/users/mennowitteveen/fo...,https://api.github.com/users/mennowitteveen/gi...,https://api.github.com/users/mennowitteveen/st...,https://api.github.com/users/mennowitteveen/su...,https://api.github.com/users/mennowitteveen/orgs,https://api.github.com/users/mennowitteveen/repos,https://api.github.com/users/mennowitteveen/ev...,https://api.github.com/users/mennowitteveen/re...,User,public,False

In [75]:
userDF.columns

Index(['login', 'id', 'node_id', 'avatar_url', 'gravatar_id', 'url',
       'html_url', 'followers_url', 'following_url', 'gists_url',
       'starred_url', 'subscriptions_url', 'organizations_url', 'repos_url',
       'events_url', 'received_events_url', 'type', 'user_view_type',
       'site_admin'],
      dtype='object')

In [79]:
pd.Categorical(userDF['login'])

['MartinBraquet', 'xuancong84', 'Aliebc', 'Aliebc', 'udit710', ..., 'jorisvandenbossche', 'datapythonista', 'datapythonista', 'datapythonista', 'mennowitteveen']
Length: 30
Categories (23, object): ['Aliebc', 'Ev2geny', 'Gri72', 'Jaspvr', ..., 'udit710', 'xuancong84', 'ycdjun', 'yohplala']

In [80]:
userDF['login'].unique()

array(['MartinBraquet', 'xuancong84', 'Aliebc', 'udit710', 'Gri72',
       'Lituchy', 'MarcoGorelli', 'arthurlw', 'Ev2geny', 'simonaubertbd',
       'Jaspvr', 'yohplala', 'Maxence1402', 'j-hendricks',
       'pierre-eliep-met', 'himanshumahajan138', 'jorisvandenbossche',
       'ptth222', 'kpvenkat47', 'ycdjun', 'jlumpe', 'datapythonista',
       'mennowitteveen'], dtype=object)

In [ ]:
https://raw.github.com/justmarkham/DAT8/blob/master/data/chipotle.tsv

In [ ]:
https://github.com/justmarkham/DAT8/blob/master/data/beer.txt

In [ ]:
https://github.com/guipsamora/pandas_exercises/blob/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv

In [ ]:
https://github.com/vincentarelbundock/Rdatasets/blob/master/datasets.csv

In [2]:
import pandas as pd
import numpy as np

In [11]:
np.random.seed(20)
df = pd.DataFrame(np.random.randn(10,4),index=pd.date_range('2025-04-07',periods=10),columns=['a','b','c','d'])

In [12]:
df

                   a         b         c         d
2025-04-07  0.883893  0.195865  0.357537 -2.343262
2025-04-08 -1.084833  0.559696  0.939469 -0.978481
2025-04-09  0.503097  0.406414  0.323461 -0.493411
2025-04-10 -0.792017 -0.842368 -1.279503  0.245715
2025-04-11 -0.044195  1.567633  1.051109  0.406368
2025-04-12 -0.168646 -3.189703  1.120132  1.332778
2025-04-13 -0.243339 -0.130031 -0.109017  1.556186
2025-04-14  0.128778 -2.066949 -0.885493 -1.104579
2025-04-15  0.932866  2.059838 -0.934938 -1.612990
2025-04-16  0.527070 -1.551101  0.329613 -1.136527

In [13]:
df['new']=df['c']+df['d']

In [14]:
df

                   a         b         c         d       new
2025-04-07  0.883893  0.195865  0.357537 -2.343262 -1.985725
2025-04-08 -1.084833  0.559696  0.939469 -0.978481 -0.039012
2025-04-09  0.503097  0.406414  0.323461 -0.493411 -0.169950
2025-04-10 -0.792017 -0.842368 -1.279503  0.245715 -1.033787
2025-04-11 -0.044195  1.567633  1.051109  0.406368  1.457477
2025-04-12 -0.168646 -3.189703  1.120132  1.332778  2.452910
2025-04-13 -0.243339 -0.130031 -0.109017  1.556186  1.447169
2025-04-14  0.128778 -2.066949 -0.885493 -1.104579 -1.990073
2025-04-15  0.932866  2.059838 -0.934938 -1.612990 -2.547928
2025-04-16  0.527070 -1.551101  0.329613 -1.136527 -0.806913

In [15]:
df['new_col_'] = df['d'].apply(lambda x : x*10)

In [16]:
df

                   a         b         c         d       new   new_col_
2025-04-07  0.883893  0.195865  0.357537 -2.343262 -1.985725 -23.432619
2025-04-08 -1.084833  0.559696  0.939469 -0.978481 -0.039012  -9.784810
2025-04-09  0.503097  0.406414  0.323461 -0.493411 -0.169950  -4.934109
2025-04-10 -0.792017 -0.842368 -1.279503  0.245715 -1.033787   2.457152
2025-04-11 -0.044195  1.567633  1.051109  0.406368  1.457477   4.063684
2025-04-12 -0.168646 -3.189703  1.120132  1.332778  2.452910  13.327782
2025-04-13 -0.243339 -0.130031 -0.109017  1.556186  1.447169  15.561864
2025-04-14  0.128778 -2.066949 -0.885493 -1.104579 -1.990073 -11.045795
2025-04-15  0.932866  2.059838 -0.934938 -1.612990 -2.547928 -16.129902
2025-04-16  0.527070 -1.551101  0.329613 -1.136527 -0.806913 -11.365265

In [17]:
df['new_col_d_log'] = df['d'].apply(lambda x : np.log(x))

C:\Users\pravi\AppData\Local\Temp\ipykernel_25152\1384546156.py:1: RuntimeWarning: invalid value encountered in log
  df['new_col_d_log'] = df['d'].apply(lambda x : np.log(x))

In [18]:
df

,a,b,c,d,new,new_col_,new_col_d_log
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN

In [23]:
def test(x):
    if(x<0):
        return False
    else :
        return True

In [24]:
df['new_fun_col'] = df['d'].apply(test)

In [25]:
df

,a,b,c,d,new,new_col_,new_col_d_log,new_fun_col
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN,False
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN,False
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN,False
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582,True
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495,True
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266,True
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238,True
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN,False
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN,False
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN,False

In [27]:
df.sort_values(by='b',ascending=False)

,a,b,c,d,new,new_col_,new_col_d_log,new_fun_col
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN,False
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495,True
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN,False
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN,False
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN,False
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238,True
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582,True
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN,False
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN,False
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266,True

In [28]:
df.index

DatetimeIndex(['2025-04-07', '2025-04-08', '2025-04-09', '2025-04-10',
               '2025-04-11', '2025-04-12', '2025-04-13', '2025-04-14',
               '2025-04-15', '2025-04-16'],
              dtype='datetime64[ns]', freq='D')

In [29]:
df['new_index_col'] = df.index

In [30]:
df

,a,b,c,d,new,new_col_,new_col_d_log,new_fun_col,new_index_col
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN,False,2025-04-07
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN,False,2025-04-08
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN,False,2025-04-09
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582,True,2025-04-10
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495,True,2025-04-11
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266,True,2025-04-12
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238,True,2025-04-13
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN,False,2025-04-14
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN,False,2025-04-15
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN,False,2025-04-16

In [31]:
df.dtypes

a                       float64
b                       float64
c                       float64
d                       float64
new                     float64
new_col_                float64
new_col_d_log           float64
new_fun_col                bool
new_index_col    datetime64[ns]
dtype: object

In [32]:
df['year'] = df.index.year
df['day'] = df.index.day
df['month'] = df.index.month

In [33]:
df

,a,b,c,d,new,new_col_,new_col_d_log,new_fun_col,new_index_col,year,day,month
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN,False,2025-04-07,2025,7,4
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN,False,2025-04-08,2025,8,4
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN,False,2025-04-09,2025,9,4
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582,True,2025-04-10,2025,10,4
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495,True,2025-04-11,2025,11,4
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266,True,2025-04-12,2025,12,4
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238,True,2025-04-13,2025,13,4
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN,False,2025-04-14,2025,14,4
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN,False,2025-04-15,2025,15,4
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN,False,2025-04-16,2025,16,4

In [35]:
df['day_name'] = df.index.day_name()
df

,a,b,c,d,new,new_col_,new_col_d_log,new_fun_col,new_index_col,year,day,month,day_name
2025-04-07,0.883893,0.195865,0.357537,-2.343262,-1.985725,-23.432619,NaN,False,2025-04-07,2025,7,4,Monday
2025-04-08,-1.084833,0.559696,0.939469,-0.978481,-0.039012,-9.784810,NaN,False,2025-04-08,2025,8,4,Tuesday
2025-04-09,0.503097,0.406414,0.323461,-0.493411,-0.169950,-4.934109,NaN,False,2025-04-09,2025,9,4,Wednesday
2025-04-10,-0.792017,-0.842368,-1.279503,0.245715,-1.033787,2.457152,-1.403582,True,2025-04-10,2025,10,4,Thursday
2025-04-11,-0.044195,1.567633,1.051109,0.406368,1.457477,4.063684,-0.900495,True,2025-04-11,2025,11,4,Friday
2025-04-12,-0.168646,-3.189703,1.120132,1.332778,2.452910,13.327782,0.287266,True,2025-04-12,2025,12,4,Saturday
2025-04-13,-0.243339,-0.130031,-0.109017,1.556186,1.447169,15.561864,0.442238,True,2025-04-13,2025,13,4,Sunday
2025-04-14,0.128778,-2.066949,-0.885493,-1.104579,-1.990073,-11.045795,NaN,False,2025-04-14,2025,14,4,Monday
2025-04-15,0.932866,2.059838,-0.934938,-1.612990,-2.547928,-16.129902,NaN,False,2025-04-15,2025,15,4,Tuesday
2025-04-16,0.527070,-1.551101,0.329613,-1.136527,-0.806913,-11.365265,NaN,False,2025-04-16,2025,16,4,Wednesday

In [37]:
df.groupby(by='new_col_').count()

,a,b,c,d,new,new_col_d_log,new_fun_col,new_index_col,year,day,month,day_name
new_col_,,,,,,,,,,,,
-23.432619,1,1,1,1,1,0,1,1,1,1,1,1
-16.129902,1,1,1,1,1,0,1,1,1,1,1,1
-11.365265,1,1,1,1,1,0,1,1,1,1,1,1
-11.045795,1,1,1,1,1,0,1,1,1,1,1,1
-9.784810,1,1,1,1,1,0,1,1,1,1,1,1
-4.934109,1,1,1,1,1,0,1,1,1,1,1,1
2.457152,1,1,1,1,1,1,1,1,1,1,1,1
4.063684,1,1,1,1,1,1,1,1,1,1,1,1
13.327782,1,1,1,1,1,1,1,1,1,1,1,1
15.561864,1,1,1,1,1,1,1,1,1,1,1,1