In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [3]:
df.shape

(6, 4)

In [4]:
row,col = df.shape

In [5]:
row

6

In [6]:
col

4

In [7]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [8]:
df.tail(2)

        day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [9]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [10]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [11]:
df.event # or df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [12]:
type(df['event'])

pandas.core.series.Series

In [14]:
df[['event','day']]

   event       day
0   Rain  1/1/2017
1  Sunny  1/2/2017
2   Snow  1/3/2017
3   Snow  1/4/2017
4   Rain  1/5/2017
5  Sunny  1/6/2017

In [15]:
df['temperature'].max()

35

In [17]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [18]:
df[df.temperature >=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [19]:
df[df.temperature == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [22]:
df[['day','temperature']][df.temperature == df['temperature'].max()]

        day  temperature
1  1/2/2017           35

In [23]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [25]:
df.set_index('day', inplace=True)

In [26]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [27]:
df.loc['1/1/2017']

temperature      32
windspeed         6
event          Rain
Name: 1/1/2017, dtype: object